<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>hyphy-conferences</AssemblyName>
    <RootNamespace>HyphyOregon.ConferenceGenerator.Cli</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../HyphyOregon.ConferenceGenerator.Core/HyphyOregon.ConferenceGenerator.Core.csproj" />
  </ItemGroup>
</Project>
